### ISSUE TITLE
Updating owlet sensor took longer than the scheduled update interval 0:00:10

### ISSUE THREAD

**Issue by cloudbr34k84** [jlamendo/ha-sensor.owlet#27]
IN ha, i have in the logs, how do i remove it or increase the update time, or just ignore this?

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:822
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 6:04:11 pm (28 occurrences)
Last logged: 6:08:41 pm

Updating owlet sensor took longer than the scheduled update interval 0:00:10

**Comment by jlamendo** [comment]
I've never been able to figure out the root cause of this, but from my experience this error occurred as a result of Owlet having difficulty connecting to WiFi. I ended up having to make a dedicated WiFi network for Owlet that was 2.4Ghz with all modern features disabled and a shorter password/SSID and I got it to work reliably that way.
